on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: aws-actions/setup-sam@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # Build the SAM application using a container
      - name: SAM Build
        run: sam build --use-container

      # Deploy the SAM application with --guided to avoid parameter conflicts
      - name: SAM Deploy (Guided)
        run: |
          sam deploy --guided \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name sam-hello-world \
            --s3-bucket aws-sam-example-bucket \
            --capabilities CAPABILITY_IAM \
            --region us-west-1
